### ISSUE TITLE
Couldn't get running and can't find help documentation

### ISSUE THREAD

**Issue by goldingdamien** [jeremija/remote-control-server#13]
After "npm start" a list of listening IP/ports are shown. Which should I use? How do they differ?
I tried going to 127.0.0.1:3000 and the localhost alternative but the browser page showed nothing.
The console shows the following:
![remote-control-server](https://user-images.githubusercontent.com/4121813/51014576-f1b0d680-15ab-11e9-8262-53e3bc3af948.png)

**Comment by distancerunner** [comment]
I found the solution:

for understanding npm:
Open the app-main directory and look at package.json file.

there is a category "scripts"
there you find a category "build" and "js" and "css"

the solution:
if you execute "npm run build" in app-main direcotry , it will run "js" and "css" and this will generate the missing files.

restart server by using: npm start again.

Does it help?

**Comment by goldingdamien** [comment]
@distancerunner Thanks. Worked. 
This should be added to the README.md

**Comment by xi1570-krupeshanadkat** [comment]
Getting error, unable to generate index.js file :
```
> remote-control-server@1.3.3 build /Users/xeuser/Desktop/last-try/remote-control-server
> npm run css && npm run js

> remote-control-server@1.3.3 css /Users/xeuser/Desktop/last-try/remote-control-server
> node-sass src/scss/style.scss -o src/res

Rendering Complete, saving .css file...
Wrote CSS to /Users/xeuser/Desktop/last-try/remote-control-server/src/res/style.css

> remote-control-server@1.3.3 js /Users/xeuser/Desktop/last-try/remote-control-server
> browserify -t babelify src/client/index.js -o src/res/index.js

Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/xeuser/Desktop/last-try/remote-control-server/node_modules/babel-preset-react/lib/index.js while parsing file: /Users/xeuser/Desktop/last-try/remote-control-server/src/client/index.js
    at createDescriptor (/Users/xeuser/Desktop/last-try/remote-control-server/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at /Users/xeuser/Desktop/last-try/remote-control-server/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/Users/xeuser/Desktop/last-try/remote-control-server/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/xeuser/Desktop/last-try/remote-control-server/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/xeuser/Desktop/last-try/remote-control-server/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/xeuser/Desktop/last-try/remote-control-server/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Users/xeuser/Desktop/last-try/remote-control-server/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at Generator.next (<anonymous>)
    at buildRootChain (/Users/xeuser/Desktop/last-try/remote-control-server/node_modules/@babel/core/lib/config/config-chain.js:120:29)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remote-control-server@1.3.3 js: `browserify -t babelify src/client/index.js -o src/res/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remote-control-server@1.3.3 js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xeuser/.npm/_logs/2020-05-23T13_03_25_593Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remote-control-server@1.3.3 build: `npm run css && npm run js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remote-control-server@1.3.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xeuser/.npm/_logs/2020-05-23T13_03_25_614Z-debug.log
```

**Comment by xi1570-krupeshanadkat** [comment]
> @distancerunner Thanks. Worked.
> This should be added to the README.md

Could you please share index.js file generated?? It would be big help!
